apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kanban-ingress
  namespace: kanban
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    # Route /api and /ws to server, everything else to client
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: server
                port:
                  number: 3001
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: server
                port:
                  number: 3001
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client
                port:
                  number: 4175
