#!/usr/bin/env bash
# Runs on the EC2 host. Invoked by /usr/local/bin/agentboard-deploy (which
# first syncs this directory from S3), by the agentboard systemd unit at boot,
# and by the "Deploy to AWS" GitHub Actions workflow over SSM.
#
#   agentboard-deploy [<image-tag>]
#
# With no argument it re-applies the currently recorded tag, which is what makes
# a reboot converge back to the running release.
#
# Everything it needs beyond this file comes from two places: /etc/agentboard/
# instance.env (written once by Terraform's user data) and SSM Parameter Store
# (the secrets). No credentials are baked into the image or this script.
set -euo pipefail

# shellcheck disable=SC1091
. /etc/agentboard/instance.env

cd "$APP_DIR"

TAG_FILE="$APP_DIR/.image_tag"
PREV_TAG_FILE="$APP_DIR/.image_tag.prev"
HEALTH_URL="http://127.0.0.1:8080/api/health"
HEALTH_TIMEOUT_SECONDS=180
# /api/health sits behind the same bearer-token middleware as the rest of /api,
# so the loopback probe has to authenticate too. Set by render_env.
API_KEY_VALUE=""

log() { echo "[deploy] $*"; }
fail() { echo "[deploy] ERROR: $*" >&2; exit 1; }

TAG="${1:-}"
if [ -z "$TAG" ]; then
  [ -f "$TAG_FILE" ] || fail "no image tag given and no previous deploy recorded"
  TAG="$(cat "$TAG_FILE")"
  log "no tag argument, re-applying recorded tag $TAG"
fi

PREV_TAG=""
if [ -f "$TAG_FILE" ]; then PREV_TAG="$(cat "$TAG_FILE")"; fi

# Write one KEY=VALUE line into an env file.
#
# Docker Compose interpolates the values it reads from an env_file, so a literal
# '$' has to be doubled or Compose eats it along with the token that follows.
# That is not theoretical: every bcrypt hash is of the form $2a$14$<salt><hash>,
# and an un-escaped one reaches Caddy truncated, locking everyone out.
emit_env() {
  local file="$1" key="$2" value="$3"
  printf '%s=%s\n' "$key" "${value//\$/\$\$}" >> "$file"
}

# ---------------------------------------------------------------------------
# Render the env files from Parameter Store
#
# Three files rather than one, so no container sees a secret it has no use for:
#   .env        proxy + Compose interpolation (image tag, domain, login)
#   .env.app    backend secrets (agent API keys, GitHub token)
#   .env.oauth  oauth2-proxy credentials
# ---------------------------------------------------------------------------
render_env() {
  local tag="$1"
  declare -A params=()

  log "reading secrets from $SSM_PREFIX"
  while IFS=$'\t' read -r key value; do
    if [ -n "$key" ]; then params["$key"]="$value"; fi
  done < <(
    aws ssm get-parameters-by-path \
      --path "$SSM_PREFIX" --recursive --with-decryption \
      --region "$AWS_REGION" --output json |
      jq -r '.Parameters[] | [(.Name | split("/") | last), .Value] | @tsv'
  )

  # A parameter still holding the Terraform placeholder counts as unset.
  local -a missing=()
  check_required() {
    local k="$1"
    local v="${params[$k]:-}"
    if [ -z "$v" ] || [ "$v" = "REPLACE_ME" ]; then
      missing+=("$SSM_PREFIX/$k")
    fi
  }

  check_required API_KEY
  case "$AUTH_MODE" in
    basic)
      check_required BASIC_AUTH_USER
      check_required BASIC_AUTH_HASH
      ;;
    oauth)
      check_required OAUTH2_PROXY_CLIENT_ID
      check_required OAUTH2_PROXY_CLIENT_SECRET
      check_required OAUTH2_PROXY_COOKIE_SECRET
      check_required OAUTH2_PROXY_GITHUB_USER
      ;;
    *) fail "unknown AUTH_MODE '$AUTH_MODE' (expected basic or oauth)" ;;
  esac

  if [ "${#missing[@]}" -gt 0 ]; then
    printf '[deploy] ERROR: unpopulated parameters:\n' >&2
    printf '  %s\n' "${missing[@]}" >&2
    printf '[deploy] Set them with: aws ssm put-parameter --name <name> --type SecureString --value <value> --overwrite\n' >&2
    exit 1
  fi

  API_KEY_VALUE="${params[API_KEY]}"

  umask 077
  local proxy_env app_env oauth_env stamp
  proxy_env="$(mktemp "$APP_DIR/.env.proxy.XXXXXXXX")"
  app_env="$(mktemp "$APP_DIR/.env.app.XXXXXXXX")"
  oauth_env="$(mktemp "$APP_DIR/.env.oauth.XXXXXXXX")"
  stamp="# Generated by deploy.sh at $(date -Is). Edits are overwritten."
  echo "$stamp" > "$proxy_env"
  echo "$stamp" > "$app_env"
  echo "$stamp" > "$oauth_env"

  local k v
  for k in "${!params[@]}"; do
    v="${params[$k]}"
    # Skip placeholders so an unset optional secret stays genuinely unset
    # rather than becoming the literal string "REPLACE_ME".
    if [ "$v" = "REPLACE_ME" ]; then continue; fi
    # "default" means "let the provider choose" for the model override.
    if [ "$k" = "CLAUDE_MODEL" ] && [ "$v" = "default" ]; then continue; fi

    case "$k" in
      OAUTH2_PROXY_*)
        emit_env "$oauth_env" "$k" "$v" ;;
      BASIC_AUTH_USER|BASIC_AUTH_HASH)
        emit_env "$proxy_env" "$k" "$v" ;;
      API_KEY)
        # Caddy injects it on the way in; the server validates it.
        emit_env "$proxy_env" "$k" "$v"
        emit_env "$app_env" "$k" "$v" ;;
      *)
        emit_env "$app_env" "$k" "$v" ;;
    esac
  done

  # config.ts reads GITHUB_TOKEN; docker-entrypoint.sh reads GH_TOKEN.
  if [ -n "${params[GH_TOKEN]:-}" ] && [ "${params[GH_TOKEN]}" != "REPLACE_ME" ]; then
    emit_env "$app_env" GITHUB_TOKEN "${params[GH_TOKEN]}"
  fi

  # Compose reads .env for ${...} interpolation in the compose file itself,
  # which is where the image coordinates come from.
  emit_env "$proxy_env" IMAGE_TAG "$tag"
  emit_env "$proxy_env" ECR_REGISTRY "$ECR_REGISTRY"
  emit_env "$proxy_env" SERVER_REPOSITORY "$SERVER_REPOSITORY"
  emit_env "$proxy_env" WEB_REPOSITORY "$WEB_REPOSITORY"
  emit_env "$proxy_env" BOARD_DOMAIN "$BOARD_DOMAIN"
  emit_env "$proxy_env" ACME_EMAIL "$ACME_EMAIL"
  emit_env "$proxy_env" AGENTBOARD_ENABLE_BREW "${ENABLE_BREW:-0}"

  # Same-origin deployment, but the server still enforces CORS.
  emit_env "$app_env" ALLOWED_ORIGINS "https://$BOARD_DOMAIN"
  emit_env "$oauth_env" OAUTH2_PROXY_REDIRECT_URL "https://$BOARD_DOMAIN/oauth2/callback"

  mv "$proxy_env" "$APP_DIR/.env"
  mv "$app_env" "$APP_DIR/.env.app"
  mv "$oauth_env" "$APP_DIR/.env.oauth"
  chmod 600 "$APP_DIR/.env" "$APP_DIR/.env.app" "$APP_DIR/.env.oauth"
}

# ---------------------------------------------------------------------------
# Compose invocation
# ---------------------------------------------------------------------------
compose() {
  local -a files=(-f docker-compose.prod.yml)
  if [ "${CONTAINER_MODE:-0}" = "1" ]; then
    files+=(-f docker-compose.container-mode.yml)
  fi
  docker compose "${files[@]}" "$@"
}

wait_for_health() {
  local deadline=$((SECONDS + HEALTH_TIMEOUT_SECONDS))
  while [ "$SECONDS" -lt "$deadline" ]; do
    if curl -fsS --max-time 5 \
      -H "Authorization: Bearer $API_KEY_VALUE" "$HEALTH_URL" >/dev/null 2>&1; then
      log "backend healthy"
      return 0
    fi
    sleep 5
  done
  return 1
}

bring_up() {
  local tag="$1"
  log "deploying tag $tag"

  render_env "$tag"

  # The Caddyfile is selected, not templated: two complete configs ship in the
  # bundle and the active one is copied into place.
  [ -f "Caddyfile.$AUTH_MODE" ] || fail "missing Caddyfile.$AUTH_MODE in deploy bundle"
  cp "Caddyfile.$AUTH_MODE" Caddyfile
  log "auth mode: $AUTH_MODE"

  if [ "$AUTH_MODE" = "oauth" ]; then
    export COMPOSE_PROFILES=oauth
  else
    unset COMPOSE_PROFILES || true
  fi

  aws ecr get-login-password --region "$AWS_REGION" |
    docker login --username AWS --password-stdin "$ECR_REGISTRY"

  compose pull --quiet
  compose up -d --remove-orphans
}

# ---------------------------------------------------------------------------
# Deploy, with automatic rollback to the previous tag
# ---------------------------------------------------------------------------
bring_up "$TAG"

if ! wait_for_health; then
  log "health check failed after ${HEALTH_TIMEOUT_SECONDS}s"
  compose ps || true
  compose logs --tail 80 server || true

  if [ -n "$PREV_TAG" ] && [ "$PREV_TAG" != "$TAG" ]; then
    log "rolling back to $PREV_TAG"
    if bring_up "$PREV_TAG" && wait_for_health; then
      log "rollback to $PREV_TAG succeeded"
    else
      log "rollback to $PREV_TAG also failed"
    fi
  else
    log "no previous tag to roll back to"
  fi
  fail "deploy of $TAG failed"
fi

# Record the tag only after it proved healthy, so the boot-time re-apply and
# the next rollback target are both known-good.
if [ -n "$PREV_TAG" ] && [ "$PREV_TAG" != "$TAG" ]; then
  echo "$PREV_TAG" > "$PREV_TAG_FILE"
fi
echo "$TAG" > "$TAG_FILE"

# Reclaim disk: this host has a 20 GiB root volume and images are ~2 GiB each.
docker image prune -af --filter "until=72h" >/dev/null 2>&1 || true

log "deployed $TAG -> https://$BOARD_DOMAIN"
compose ps
